# Generated by Django 5.1.7 on 2025-03-21 05:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital', models.CharField(blank=True, max_length=100, null=True)),
                ('specialty', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(default='general', max_length=100)),
                ('license_number', models.CharField(blank=True, max_length=50, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OCTImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_file', models.ImageField(upload_to='oct_images/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('custom_id', models.CharField(blank=True, max_length=50, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oct_images', to='api.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('classification', models.CharField(max_length=100)),
                ('findings', models.TextField()),
                ('analysis_image', models.ImageField(blank=True, null=True, upload_to='analysis_images/')),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('oct_image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_result', to='api.octimage')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comments', models.TextField()),
                ('review_date', models.DateTimeField(auto_now_add=True)),
                ('analysis_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='api.analysisresult')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.doctor')),
            ],
        ),
    ]
