# Generated by Django 5.1.7 on 2025-03-21 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_review_analysis_result_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='review',
            name='analysis_result',
        ),
    ]
